spring.application.name=hireFlowProject
server.port=8081
my.test.property=Digvijay
spring.data.mongodb.uri=mongodb+srv://karandedigvijay2_db_user:Uh6W7q2wu19gD6cU@cluster0.qegqh88.mongodb.net/hireFlowDB?retryWrites=true&w=majority&appName=Cluster0
########################################
# cloudinary
########################################

cloudinary.cloud-name=dpzobapgz
cloudinary.api-key=565624929481914
cloudinary.api-secret=XFnG3zWYvmu1TWVQtr8WzaWDsms
########################################
# Redis
########################################

spring.data.redis.host=microclear-fruitful-payment-69952.db.redis.io
spring.data.redis.port=10132
spring.data.redis.username=default
spring.data.redis.password=MT3cKmDQVltCBbllPLgAjfvCu5oR2QLr
spring.data.redis.ssl.enabled=true
########################################
# Email service
########################################

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=karandedigvijay2@gmail.com
spring.mail.password=pgpenodezrmpaoob
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true